### ISSUE TITLE
Missing separator in generated YAML

### ISSUE THREAD

**Issue by philippemerle** [same7ammar/kube-composer#24]
Very nice on-line composer! I created two deployments and the generated yaml is as follows
```yaml
# Kubernetes Configuration
# Generated by Kube Composer
# Deployments: 2
# Total Containers: 2
# Ingress Resources: 1

# === MY-APP DEPLOYMENT ===
# Containers: 1
# Ingress: Enabled
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        -
          name: app
          image: 
          ports:
            -
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: default
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
    -
      port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP


# === MY-APP2 DEPLOYMENT ===
# Containers: 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app2
  namespace: default
  labels:
    app: my-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app2
  template:
    metadata:
      labels:
        app: my-app2
    spec:
      containers:
        -
          name: app
          image: 
          ports:
            -
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-app2-service
  namespace: default
  labels:
    app: my-app2
spec:
  selector:
    app: my-app2
  ports:
    -
      port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
```

A separator `---` must be put before line `# === MY-APP2 DEPLOYMENT ===` else the second Deployment resource crushes the first Service resource.
